### ISSUE TITLE
[Bug]:  AGO has Bug in sneak animation

### ISSUE THREAD

**Issue by sensirou** [Monitor221hz/Pandora-Behaviour-Engine-Plus#142]
Version

1.2.1 alpha

### Provide Instructions on Reproducing the Problem

Moving in sneak with bow in hand will make the character look like an chimpanzee.

### Provide   ##Relevan
[engne log.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14567130/engne.log.zip)
t Files

### Provide Visual Proof (optional)

![enb2024_3_11_18_59_32](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/65520795/c80bcdf8-ac40-4747-bbe6-1772ece754ee)
![2](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/65520795/16abf0b2-e576-4412-95d0-88c721a4a7a4)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Do you have XPMSE installed? If you do have the mod installed do you have the XPMSE patch active? @sensirou

**Comment by sensirou** [comment]
yes, I have XPMSE installed, and also have AGO patch for nemesis. I also check in XPMSE option when running Pandora
![Untitled](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/65520795/be156aa6-736f-4d7d-af44-eeacb6b8b4f8)

**Comment by jkallial** [comment]
Ever find a fix for this? Having the same issue?
