### ISSUE TITLE
[Bug]: CTD after the game starts at my clear Test Build

### ISSUE THREAD

**Issue by Jacksop9999** [Monitor221hz/Pandora-Behaviour-Engine-Plus#204]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

 v1.4.2-alpha

### Provide Instructions on Reproducing the Problem

CTD after the game starts (Paradigm - A Quick Start Overhaul) and during the dragon flythrough. 

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15080275/Pandora_Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
Can you test this debug build of Pandora to see if the issue is fixed?

 https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/actions/runs/8805065194/artifacts/1440489288

**Comment by Jacksop9999** [comment]
[overwrite.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15081795/overwrite.zip)

Installed this version. Still getting CTD 100% of the time within the first 60 seconds of starting.

**Comment by Monitor144hz** [comment]
@Jacksop9999 have you confirmed this issue is not present on Nemesis output? I'm looking at the log now and it doesn't seem to be behavior related at a glance.

**Comment by Jacksop9999** [comment]
https://youtu.be/0ZBP9o-P0m8  You have to wait a while for the video to process. If I'm doing everything right, I don't even know what else the problem is. I haven't encountered a CTD in a long time, because I check everything very carefully.

**Comment by Monitor144hz** [comment]
@Jacksop9999 delete the `dragonproject~dragonbehavior` folder in `Pandora_Engine/mod` for now, I'm looking into the issue
