### ISSUE TITLE
[Bug]: Vortex "Failed to run tools"

### ISSUE THREAD

**Issue by Euphanian** [Monitor221hz/Pandora-Behaviour-Engine-Plus#213]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

1.4.3

### Provide Instructions on Reproducing the Problem

 1. Follow the Pandora Vortex instructions by installing the Pandora outside the mods folder (anywhere outside the Data folder I assumed.)
 2. Start Pandora and tick patches
 3. Click "launch", then Pandora will close.
 4. Vortex shows an error message of "Failed to run tools"
 
If I install Pandora as a mod into Vortex, things will work fine.

### Provide Relevant Files

INFO : Skyrim Patcher 1.4.2-alpha
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
WARN : Dispatcher > "Ice skating fixed for real" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
INFO : Pandora Mod 1 : Precision - v.1.0.0
INFO : Pandora Mod 2 : Ice skating fixed for real - v.1.0.0
INFO : Pandora Mod 3 : True Directional Movement - 360 Horse Archery - v.1.0.0
INFO : Pandora Mod 4 : True Directional Movement - Procedural Leaning - v.1.0.0
INFO : Pandora Mod 5 : True Directional Movement - Headtracking - v.1.0.0
INFO : Pandora Mod 6 : Pandora Base - v.1.0.0

### Provide Visual Proof (optional)

https://ibb.co/Nt0tHwX

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by kanapuro** [comment]
+1 could only use it properly if i downloaded it the way instructed AND dragged the 7zip into vortex. very frustrating
