### ISSUE TITLE
[Chore]: Upgrade from .NET 7 to .NET 8

### ISSUE THREAD

**Issue by Monitor221hz** [Monitor221hz/Pandora-Behaviour-Engine-Plus#224]

**Comment by elbadcode** [comment]
I have mine cross compiling net 8 and net 9. didnt really take anything aside from upgrading nuget packages. I also packed mine into a framework independent exe although I need to rebuild to account for a month or so of updates but I can share all that if helpful later. I think I can set up the upgrade as a github action

**Comment by Monitor221hz** [comment]
.
