### ISSUE TITLE
[Bug]: CTD during Miraak

### ISSUE THREAD

**Issue by Gonzeh** [Monitor221hz/Pandora-Behaviour-Engine-Plus#234]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

1.5.1-alpha

### Provide Instructions on Reproducing the Problem

When doing the Dragonborn quest and you 1st meet Miraak, when he tries to get on the Dragon at the end of the scene the game CTDs. Tried with an older version of Pandora and the scene won't finish as the animation doesn't trigger for Miraak to climb on.

### Provide Relevant Files

Engine log:

WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED

[Crash_2024_6_6_16-49-12.txt](https://github.com/user-attachments/files/15655580/Crash_2024_6_6_16-49-12.txt)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Gonzeh** [comment]
Further testing:

Using 1.5.0 stops the crash BUT Miraak just stands there unable to mount the Dragon. Also noticed 1.5.1 breaks the right click attack on Bow Rapid Combo but 1.5.0 works fine for that. 

1.5.0 log for fails:

ERROR : Nemesis Assembler > File G:\Skyrim - Backup\data\Nemesis_Engine\mod\colisc\draugrbehavior\#0115.txt > Load > FAILED > The 'hkobject' start tag on line 1 position 4 does not match the end tag of 'hkparam'. Line 11, position 5.
ERROR : Nemesis Assembler > File G:\Skyrim - Backup\data\Nemesis_Engine\mod\colisc\draugrbehavior\#0119.txt > Load > FAILED > The 'hkobject' start tag on line 1 position 4 does not match the end tag of 'hkparam'. Line 11, position 5.
WARN : Dispatcher > "HotKeySkill" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Validator > defaultfemale~magicbehavior > Duplicate Variable > bAllowRotation > Index > 9 > REMOVED
WARN : Dispatcher > "Jump Behavior Overhaul" > defaultmale~0_master > Replace > Element > #0260/event/Element0/id > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > Index > 136 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > Index > 118 > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Cancel > Index > 0 > REMOVED

**Comment by Monitor144hz** [comment]
There's virtually no difference between 1.5.1a and 1.5.0a except for the version code that's printed in the logs. I have an update for dragons coming next version.
