### ISSUE TITLE
[Bug]:Modern Stagger Lock stagger animation does not produce displacement

### ISSUE THREAD

**Issue by neeeetuo** [Monitor221hz/Pandora-Behaviour-Engine-Plus#238]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.3

### Provide Instructions on Reproducing the Problem

I apologize for the unchecked report.
In 1.0, MSLF and MaxsuPoise cannot be triggered, I mistakenly confused the two of them. I thought that MSLF can be used normally.
 1.4.3 In my test, MaxsuPoise can be triggered normally, but MSLF animation cannot be shifted. For example, when I am attacked, the character will not fly away. I'm rolling in place.
And sorry again for my carelessness.

### Provide Relevant Files

[Engine.log](https://github.com/user-attachments/files/15861839/Engine.log)
[PANDORA PUT OUTfnis.ZIP](https://github.com/user-attachments/files/15861969/PANDORA.PUT.OUTfnis.ZIP)

### Provide Visual Proof (optional)

https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/96467273/ef15dcca-d26d-4d39-bc28-92cb2c9e32b1

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by EIKICHIONI** [comment]
man! what can i say? i tall you he not fixed this bug. @neeeetuo

**Comment by EIKICHIONI** [comment]
@Monitor221hz in v1.6 can you fixed this bug?

**Comment by EIKICHIONI** [comment]
https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/96964090/d51dc6a8-30cb-4945-9aca-7280a6d47795

**Comment by EIKICHIONI** [comment]
https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/96964090/01f9336b-66d6-4412-ba65-c2f034eb5b76

**Comment by EIKICHIONI** [comment]
https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/96964090/64417a21-df54-409f-93c8-e7627a3b007c

**Comment by neeeetuo** [comment]
Did I say something wrong? Why is this question not being heard? I'm sorry if I offended you. I had no idea about the various feuds between mod writers.

**Comment by neeeetuo** [comment]
Did I say something wrong? Why is this question not being heard? I'm sorry if I offended you.

**Comment by weizhen199** [comment]
> Did I say something wrong? Why is this question not being heard? I'm sorry if I offended you.

No, it is true. But Monitor114514hz need time to fix it.
