### ISSUE TITLE
can pandora load py scripts like nemesis?

### ISSUE THREAD

**Issue by jokery-sky** [Monitor221hz/Pandora-Behaviour-Engine-Plus#242]
### Expected behavior

pandora is fast and stable which make me want to use it,but the problem is pandora did not load the py script(pls refer to the screenshot),therefore 
some of the script are not functioning.

![20240702130239](https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/174408136/2ffd647c-a387-4d68-9406-3afd6266e1f3)

### other

related MOD FNIS Sexy Move SE 7.2https://www.nexusmods.com/skyrimspecialedition/mods/13303

**Comment by Monitor221hz** [comment]
no
