### ISSUE TITLE
[Feature]: Send a message in the message log when the launch has started/show progress while it runs

### ISSUE THREAD

**Issue by iwejfnd** [Monitor221hz/Pandora-Behaviour-Engine-Plus#243]
### Expected behavior

Currently, when I press "Launch", I have no idea if it's running until it finishes and dumps the whole progress log in the message box.
When "Launch" is pressed, it would be nice to get a quick confirmation message just to show that it was pressed. Seems simple, I know, but sometimes the loads take 15 seconds, sometimes they take a couple minutes, so knowing that the button was actually pressed would be great.
No clue how the program actually functions, maybe some sort of progress update would help as well? Thanks either way, enjoying how much quicker this is compared to nemesis.

**Comment by BeermotorWB** [comment]
This was functional in previous releases so it might be a regression.

**Comment by Monitor221hz** [comment]
Yes, it was a minor regression. It has been restored in the latest version, which has not yet been pushed to a release.

**Comment by Monitor221hz** [comment]
Should be restored in the latest version.
