### ISSUE TITLE
[Bug]: Pandora does not stay open - can't get it to run

### ISSUE THREAD

**Issue by Psymon-Prime** [Monitor221hz/Pandora-Behaviour-Engine-Plus#244]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

Pandora Behaviour Engine v1.5.1-alpha

### Provide Instructions on Reproducing the Problem

I recently got clued into using pandora instead of Nemesis. I removed Nemesis. Installed Pandora (as a mod according to it's instructions). I am using wrye bash, but I made sure all components are where they need to go. I'm not noob at installing, just installing for skyrim I'm not that familiar yet. I'm willing to deal with the consequences of having to manually manage whatever it does. I know how MO2 works, but I'm old hand at wrye bash having been a beta tester under wrye.

I updated .NET as it requested. Windows 10 latest version if that matters.

Trying to launch it and it shows as active in the task manager, but then closes right away. Trying to run as admin and it gives more notices and having to click through running it anyway, but same behavior it closes soon after starting? IDK why. There are no notices in defender that would then allow me to make an exception. 

I have looked but don't see that any kind of log is created, but I could be wrong and just not looking in the correct place.

Some help here? thanks

### Provide Relevant Files

Tell me where to find the log and I will include it....I can't find it, If I do find it I will edit this report.

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Update to the latest version
