### ISSUE TITLE
[Bug]: critical error: engine launched with configuration SE/AE even though I have AE patches for mods like Paraglider

### ISSUE THREAD

**Issue by MazelNut** [Monitor221hz/Pandora-Behaviour-Engine-Plus#245]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

1.5.1-alpha

### Provide Instructions on Reproducing the Problem

I downloaded Hot Key SKill, Better Jumping, Jump Attack, Spirit Attack and Paraglider, as well as corresponding AE patches for those mods if it said they were needed. I am on the latest AE edition. I have also noticed that despite patching MCO and DCMO I still can't dodge. There is also some animations from Immersive Interactions not working...but no patch shows for that and I have heard from others that for some reason it is just not compatible with Pandora.
[ActiveMods.txt](https://github.com/user-attachments/files/16106393/ActiveMods.txt)

### Provide Relevant Files

[Engine.log](https://github.com/user-attachments/files/16106238/Engine.log)
[Pandora_Behaviour_Engine_v1.5.1-alpha.zip](https://github.com/user-attachments/files/16106264/Pandora_Behaviour_Engine_v1.5.1-alpha.zip)

### Provide Visual Proof (optional)

![Screenshot (970)](https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/assets/174777206/7eb4d0f3-7fc4-4302-8661-ad22f812e567)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/issues/47#issuecomment-1873468727

See this link for a solution. It's not an engine issue, it's a mod issue.
