### ISSUE TITLE
[Bug]: Skeletons are A-posing

### ISSUE THREAD

**Issue by Yrbaa** [Monitor221hz/Pandora-Behaviour-Engine-Plus#247]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.5.1

### Provide Instructions on Reproducing the Problem

Skeletons, for example from the dawnguard dlc in the castle or soul cairn, are just a-posing when they are in their idle animation before spotting the player. Hitting them resets them and makes them act correctly. 

### Provide Relevant Files

[Pandora.zip](https://github.com/user-attachments/files/16273297/Pandora.zip)

### Provide Visual Proof (optional)

![ScreenShot34](https://github.com/user-attachments/assets/f8d72f4f-086b-40f4-99ac-bc9dc7907c3d)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Have you tried the latest version?

**Comment by Yrbaa** [comment]
yep just tried v2.0.4 and the issue is still here. I removed old Pandora and replaced it with new and also removed the old output.

**Comment by iwejfnd** [comment]
Just want to add that I'm also getting this issue with skeletons - I first noticed an issue because horses were in a sort of A-pose as well. Using 2.0.4.
![horse](https://github.com/user-attachments/assets/57951c66-0164-4174-9f01-308a91820234)
