### ISSUE TITLE
[Bug]: Catastrophic backtracking of multiline comments in FNIS Animlist regex leading to engine freezes with certain mods.

### ISSUE THREAD

**Issue by gradashy** [Monitor221hz/Pandora-Behaviour-Engine-Plus#251]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.6.0 Alpha

### Provide Instructions on Reproducing the Problem

When trying to run nothing happens, it stays locked in the start in the engine, Rollback to the older version v1.5.1, and works as normal.

Using Skyrim VR, I have .net 8 installed and working

### Provide Relevant Files

it generates nothing

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by InvIMj** [comment]
Not only VR. Also on regular version SE 1.5.97.0

**Comment by L-W-C00** [comment]
+1，click launch, output"Engine launched with configuration: Skyrim SE/AE",and nothing happend.

**Comment by qx12** [comment]
also

**Comment by qx12** [comment]
+1

**Comment by Monitor221hz** [comment]
Have you tried clearing past output? And could someone post a list of all the FNIS mods they're using? As that's that only component that had major changes this version.

**Comment by qx12** [comment]
I cleaned already and The latest version of the NET file is installed.Character have animation in game,but some special animation have no effect,example dance.Additionally,ZAZ mods always likes this.

**Comment by Monitor221hz** [comment]
Please update to [the latest version](https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/releases/latest) and retest the engine.

**Comment by Monitor221hz** [comment]
> Character have animation in game,but some special animation have no effect,example dance.Additionally,ZAZ mods always likes this.
Is the dance animation an ofa type animation? Animations that only play on arms via FNIS animlist should be compatible now.

**Comment by mydoom13** [comment]
v1.6.1-alpha the same as in version 1.6.0 tells me "Engine launched with configuration: Skyrim SE/AE" instead of a list of registered animations. In the game itself, any sexlab animations do not start.

**Comment by InvIMj** [comment]
> v1.6.1-alpha the same as in version 1.6.0 tells me "Engine launched with configuration: Skyrim SE/AE" instead of a list of registered animations. In the game itself, any sexlab animations do not start.

Same.

**Comment by Monitor221hz** [comment]
> v1.6.1-alpha the same as in version 1.6.0 tells me "Engine launched with configuration: Skyrim SE/AE" instead of a list of registered animations. In the game itself, any sexlab animations do not start.

It sends that when the engine has started running. Did you wait for it to finish?

**Comment by mydoom13** [comment]
It displays this message immediately after start. I didn't wait very long as it used to take 6-7 seconds. but I waited about 30-40 seconds for sure.

**Comment by Monitor221hz** [comment]
> It displays this message immediately after start. I didn't wait very long as it used to take 6-7 seconds. but I waited about 30-40 seconds for sure.

Can you post the engine.log?

**Comment by Monitor221hz** [comment]
Alright, I found the issue. Catastrophic backtracking with the regex used to match animline. Should be fixed next version.

**Comment by mydoom13** [comment]
[Engine.log](https://github.com/user-attachments/files/16324585/Engine.log)
Here. but there is only one entry "INFO : Skyrim Patcher 1.6.1-alpha"

**Comment by Monitor221hz** [comment]
Please test with [this experimental build](https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/actions/runs/10028819130/artifacts/1723262822) And let me know if the problem persists.

**Comment by Monitor221hz** [comment]
The issue was closed as the problem seems to be solved, but do let me know if the issue remains.

**Comment by mydoom13** [comment]
I pressed Launch, waited a minute and went for a walk with the dog. ) When I returned, the process was completed successfully. "Launch finished in 925.87 seconds"!! It’s not surprising that we didn’t wait until the end, deciding that it didn’t work. Previously it took 6 seconds)

**Comment by Monitor221hz** [comment]
> I pressed Launch, waited a minute and went for a walk with the dog. ) When I returned, the process was completed successfully. "Launch finished in 925.87 seconds"!! It’s not surprising that we didn’t wait until the end, deciding that it didn’t work. Previously it took 6 seconds)

oh my god

**Comment by Monitor221hz** [comment]
this seems to be a separate issue; I've moved it into #255

**Comment by Monitor221hz** [comment]
@mydoom13 are you on a HDD or SSD?

**Comment by mydoom13** [comment]
> @mydoom13 are you on a HDD or SSD?
ssd

**Comment by mydoom13** [comment]
I gave the latest version to a friend and his animations took 974 seconds to generate. he also has ssd

**Comment by Monitor221hz** [comment]
@mydoom13 please send your Engine.log

**Comment by mydoom13** [comment]
[Engine.log](https://github.com/user-attachments/files/16325347/Engine.log)

**Comment by Monitor221hz** [comment]
@mydoom13 that's not the latest version; can you retest with v1.6.3-alpha and not v1.6.2-alpha, and then post the new engine.log?

**Comment by mydoom13** [comment]
> @mydoom13 that's not the latest version; can you retest with v1.6.3-alpha and not v1.6.2-alpha, and then post the new engine.log?
oh sorry, I didn't see the update. I installed and launched. as long as he does his job. Apparently it's still not fast.

**Comment by mydoom13** [comment]
[Engine.log](https://github.com/user-attachments/files/16325417/Engine.log)
Here. 1.6.3 became faster. 250 seconds

**Comment by InvIMj** [comment]
1.6.3 Works like a charm, with fast generation times.
Only thing I noticed, was Let Your Hair Down's animation, makes the character T-Pose for awhile.

**Comment by TOHgoat** [comment]
still not work for me,it generates nothing.

**Comment by mydoom13** [comment]
> 1.6.3 Works like a charm, with fast generation times. Only thing I noticed, was Let Your Hair Down's animation, makes the character T-Pose for awhile.

How many seconds does Pandora take you to work? I'm on my last launch "Launch finished in 223.13 seconds" In version 1.5.1 it took me 6 seconds with the same set of mods.

**Comment by mydoom13** [comment]
> still not work for me,it generates nothing.

Are you waiting long enough? this may take up to 15 minutes.

**Comment by TOHgoat** [comment]
I promise I waited for more than 15 minutes, but it still didn't generate anything, the Engine.log is empty.

**Comment by InvIMj** [comment]
> > 1.6.3 Works like a charm, with fast generation times. Only thing I noticed, was Let Your Hair Down's animation, makes the character T-Pose for awhile.
> 
> How many seconds does Pandora take you to work? I'm on my last launch "Launch finished in 223.13 seconds" In version 1.5.1 it took me 6 seconds with the same set of mods.

About 5-6 secs, give or take.
Pretty fast overall.

**Comment by mydoom13** [comment]
> > > 1.6.3 Works like a charm, with fast generation times. Only thing I noticed, was Let Your Hair Down's animation, makes the character T-Pose for awhile.
> > 
> > 
> > How many seconds does Pandora take you to work? I'm on my last launch "Launch finished in 223.13 seconds" In version 1.5.1 it took me 6 seconds with the same set of mods.
> 
> About 5-6 secs, give or take. Pretty fast overall.

oh, how many animations does it register with you? I have 64k animations.

**Comment by InvIMj** [comment]
> > > > 1.6.3 Works like a charm, with fast generation times. Only thing I noticed, was Let Your Hair Down's animation, makes the character T-Pose for awhile.
> > > 
> > > 
> > > How many seconds does Pandora take you to work? I'm on my last launch "Launch finished in 223.13 seconds" In version 1.5.1 it took me 6 seconds with the same set of mods.
> > 
> > 
> > About 5-6 secs, give or take. Pretty fast overall.
> 
> oh, how many animations does it register with you? I have 64k animations.

![1](https://github.com/user-attachments/assets/ef728c7e-8662-4e49-9613-dacbf1639771)

**Comment by MaskPlague** [comment]
For 1.5.1 generation time is 4.6 seconds with 37k animations. For 1.6.0, 1.6.1, 1.6.2, and 1.6.3, I haven't successfully run the engine once giving 20 minutes to each version and the Engine log is empty for each version. Eagerly awaiting optimization. ;-;
