### ISSUE TITLE
[Bug]: loot  error for animated eating redux

### ISSUE THREAD

**Issue by dutchblizzard** [Monitor221hz/Pandora-Behaviour-Engine-Plus#259]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

1.6.3-alpha

### Provide Instructions on Reproducing the Problem

![image](https://github.com/user-attachments/assets/06bc8a77-4b84-4c16-acb5-d3a8fbdf75b5)
i have run pandora and ticked all i needed

### Provide Relevant Files

[Engine.log](https://github.com/user-attachments/files/16402729/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Not a bug with the engine, this concerns LOOT metadata.
