### ISSUE TITLE
[Bug]: Skyrim CTD with Engine.log warnings

### ISSUE THREAD

**Issue by evocation01** [Monitor221hz/Pandora-Behaviour-Engine-Plus#261]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.5.1-alpha

### Provide Instructions on Reproducing the Problem

Using Skyrim SE 1.6.1170 and MO v2.5.0.
I was using Nemesis, switched to Pandora because of slowness/stuck at 99%. Yes, Nemesis file is deactivated as well. Tried deleting it too. 
Pandora launched perfectly with 37k total animations (about same as nemesis), skyrim launches, but when clicking new game it crashes after 2-3 seconds (when loading, the loading animations start).
Of course, I am using a lot of mods. I would love if u have any ideas, so I don't have to troubleshoot one by one.

I tried to troubleshoot by using John95ac's AnimForgePatcher mod as a ZaZ/CGO patch, which worked. (ZaZ was included as a warning beforehand, in the Engine.log)
Also, I tried using latest v1.6.3 patch. Same issue, included ZaZ as well. Fixed it with AnimForgePatcher.

I am also adding crash logs with reports created by CLA SSE - Crash Log Analyzer (4 reports) and my mod list.
FYI, deactivating Animated Mounted Casting didn't fix anything.

Thank you.

Credits
https://www.nexusmods.com/skyrimspecialedition/mods/122055?tab=description for AnimForgePatcher
https://www.nexusmods.com/skyrimspecialedition/mods/89860?tab=description for Crash Analyzer

### Provide Relevant Files

[Pandora Output.zip](https://github.com/user-attachments/files/16419161/Pandora.Output.zip)
[crash logs.zip](https://github.com/user-attachments/files/16419184/crash.logs.zip)
[mod_list_MO2.txt](https://github.com/user-attachments/files/16419213/mod_list_MO2.txt)

Engine.log warnings:

INFO : Skyrim Patcher 1.5.1-alpha
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
WARN : Dispatcher > "Animated Mounted Casting" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
WARN : Validator > defaultmale~0_master > Duplicate Event > OST_ExitAnim > Index > 630 > REMOVED
WARN : Validator > defaultmale~0_master > Duplicate Event > OST_ExitAnim > Index > 435 > REMOVED
WARN : Validator > defaultmale~0_master > Duplicate Event > OST_ExitAnim > Index > 420 > REMOVED
WARN : Validator > defaultmale~0_master > Duplicate Event > OST_ExitAnim > Index > 41 > REMOVED

### Provide Visual Proof (optional)

![2024-07-30 00_03_48-](https://github.com/user-attachments/assets/28bbab3c-af6c-48eb-903c-66703707517e)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
> Skyrim Patcher 1.5.1-alpha

Update to the latest version.
