### ISSUE TITLE
[Bug]: Animations not showing up in Pandora

### ISSUE THREAD

**Issue by Sapphire371-173** [Monitor221hz/Pandora-Behaviour-Engine-Plus#263]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.0.1-alpha

### Provide Instructions on Reproducing the Problem

My animations just don't show up. I have installed Pandora outside of my mods folder in my base game directory, but animations I used to use with Pandora simply don't show up, so I can't even launch them into my game. I'm not sure what I could be doing wrong. I have some of Vanargands animations installed, along with animations for OStim Standalone
I should also note that I installed it in my base game directory into its own folder when I first noticed the issue, then I deleted that folder and everything in it (everything that came with pandora), then reinstalled it but left the files loose in my base game directory (which still didn't work). I then installed it through my Vortex mod manager, and when I opened the data folder and tried to run pandora from there the application was empty and CTD when I pressed Launch.
I'm still relatively new to Pandora so the issue might be simple, but please let me know if I'm missing anything, or if I need to uninstall and start over.

### Provide Relevant Files

Engine Log: https://pastebin.com/NJ5EyFiK

### Provide Visual Proof (optional)

![Screenshot 2024-08-01 123300](https://github.com/user-attachments/assets/80be59fc-c418-4b99-af52-54ff7942c847)
Despite having animations installed, they don't appear here (the one located in the SKSE folder)
![Screenshot 2024-08-01 124730](https://github.com/user-attachments/assets/5108ce53-6b3f-4216-8774-ce3758820f47)
This one is just empty (in the data folder).

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
> Despite having animations installed, they don't appear here (the one located in the SKSE folder)

> This one is just empty (in the data folder).

Could you show the relevant folder paths? I'd like to help, but I know Vortex users who use Pandora successfully so this must be something on the user end? Not something I can control as I don't develop Vortex nor can I remotely control your computer :(

**Comment by Sapphire371-173** [comment]
> > Despite having animations installed, they don't appear here (the one located in the SKSE folder)
> 
> > This one is just empty (in the data folder).
> 
> Could you show the relevant folder paths? I'd like to help, but I know Vortex users who use Pandora successfully so this must be something on the user end? Not something I can control as I don't develop Vortex nor can I remotely control your computer :(

Sure thing! Is there a particular way I should do this? If not, that first screenshot is from :C>ProgramFilesx86>Steam>Steamapps>Common>Skryim Special Edition and the second one is from :C>ProgramFilesx86>Steam>Steamapps>Common>Skryim Special Edition>Data

Slight update though, I managed to get the actual exe working by cutting the exe from the SKSE folder and pasting it into the data folder, replacing application there, so it does seem like the error was on my end! It seems like it was bc I hadn't placed Pandoras contents in the data folder directly. While everything does seem to be working, I'm not sure if there's anything I should worry about regarding the duplicate files? If not, feel free to close this!

**Comment by Monitor221hz** [comment]
There should be nothing to worry about for duplicate files.
