### ISSUE TITLE
[Bug]: MCO light-heavy attack combo system not working

### ISSUE THREAD

**Issue by MaxSkar** [Monitor221hz/Pandora-Behaviour-Engine-Plus#264]
### Check for duplicate issues

- [ ] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.0.1

### Provide Instructions on Reproducing the Problem

cant power make the power attack combo finisher (or even follow up) after executing 1 or more light attacks. Im using the latest verion of MCO to the date and the elden ring moveset W dual swords.

### Provide Relevant Files

dont know where is it, sorry.

### Contributing To Development

- [ ] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Can you please check the latest version? As of the time of writing that is v2.0.4-alpha.

**Comment by MaxSkar** [comment]
yup, its working now, i think my entire mod list works on pandora only now, im looking to dump nemesis once and for all, i will keep posting the bugs i find, thank you very much, this program its awesome

**Comment by Monitor221hz** [comment]
Thanks for your report.
