### ISSUE TITLE
[Bug]: When I unsheathe my weapon my character does every action/animation, I have a patch for.

### ISSUE THREAD

**Issue by MaskPlague** [Monitor221hz/Pandora-Behaviour-Engine-Plus#267]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.0.1

### Provide Instructions on Reproducing the Problem

I ran the latest version of Pandora (2.0.1) with all of my patches in the same order as I had them for 1.5.1 and when in game as soon as I drew my sword and walked forward my character air-dashed and deployed their paraglider. Afterward, they continually deploy their paraglider or air dash and cannot re-sheathe their weapon. I tried seeing if Xing's Falling Art behavior patch was the problem but when I uninstalled it my character would instead activate a killmove from Thick Thighs Take Lives and then spam light attacks whenever I moved my character.  Interestingly while my weapon was sheathed everything worked fine.

### Provide Relevant Files

Here is my Pandora Output for 1.5.1 (the latest version that worked at all for me.)
[1.5.1 Pandora Output.zip](https://github.com/user-attachments/files/16469419/1.5.1.Pandora.Output.zip)

Here is my Pandora Output for 2.0.1
[2.0.1 Pandora Output.zip](https://github.com/user-attachments/files/16469421/2.0.1.Pandora.Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Can you please check the latest version? As of the time of writing that is v2.0.4-alpha.

**Comment by MaskPlague** [comment]
Everything appears to be working thanks!

**Comment by MaskPlague** [comment]
Everything appears to be working thanks!
