### ISSUE TITLE
[Bug]: Engine just crashes.

### ISSUE THREAD

**Issue by InvIMj** [Monitor221hz/Pandora-Behaviour-Engine-Plus#272]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

Since v2.0.0-alpha and later versions,

### Provide Instructions on Reproducing the Problem

ΜΟ2 User.
Everything looks ok at first, my animations show up, but when I click LAUNCH, Pandora just crashes.
No message, no generation no nothing.

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/user-attachments/files/16475431/Pandora_Output.zip)

It says in the Engine.log that it's version number is 1.6.3a but i used 2.0.4a

### Provide Visual Proof (optional)

https://github.com/user-attachments/assets/71ebe385-20f9-4ae0-a55e-a2800928bf7e

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
When updating Pandora, did you choose the "Merge" option rather than the "Replace" option in MO2? Or did you copy and paste the new files over the old ones and clicked yes to replacements? 

Some unneeded template behavior files that were in versions before 2.0.0-alpha were removed from the release because they were causing similar engine crashes with the new backend.

**Comment by InvIMj** [comment]
Yea I was copy/pasting. After i removed every old file, and replaced it with the new, everything worked perfectly.
I get some warnings [FAILED] in the Engine.log about some animations.

Is it something to be ignored or is it some kind of error?

[Engine.log](https://github.com/user-attachments/files/16478943/Engine.log)

**Comment by Monitor221hz** [comment]
The warnings are nothing to be worried about, unless they have a discernible impact in-game.
