### ISSUE TITLE
[Bug]: dual magic cast animations not working correctly

### ISSUE THREAD

**Issue by MaxSkar** [Monitor221hz/Pandora-Behaviour-Engine-Plus#273]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.0.4

### Provide Instructions on Reproducing the Problem

when i use dual casted magic (the starter fire spell) the left hand stays at the waist size instead of being in front of the character like the right hand, im using goetia magic spell casting animations and i didnt unlock the dual cast perk yet.

### Provide Relevant Files

didnt have it

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Did you check to make sure the XPMSE patch was ticked?

**Comment by MaxSkar** [comment]
> Did you check to make sure the XPMSE patch was ticked?

yup
![image](https://github.com/user-attachments/assets/6164ae36-65d3-4c5a-8581-7ce4fa22e617)

**Comment by Monitor221hz** [comment]
![image](https://github.com/user-attachments/assets/9a8fce88-4d30-4874-9401-362a9c6c587f)

I need output files to diagnose the issue.

**Comment by MaxSkar** [comment]
> ![image](https://private-user-images.githubusercontent.com/89633536/355072019-9a8fce88-4d30-4874-9401-362a9c6c587f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTU3MzEsIm5iZiI6MTcyMjkxNTQzMSwicGF0aCI6Ii84OTYzMzUzNi8zNTUwNzIwMTktOWE4ZmNlODgtNGQzMC00ODc0LTk0MDEtMzYyYTljNmM1ODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMzcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMmIxODkzM2Q0NmQzZjFjZjRhYzA2ZTlkZDU4NGRkNTFlZWNkYjFjZmZmNjYwYTAyZTg3ODNjNGViZDU5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HLiOJ2MtE-wFQR7YXSMYOrIyVrR5MKjVMJj0xgy-H4Q)
> 
> I need output files to diagnose the issue.

im not so experienced in this type of things, can you provide me what the default path of the output files should be? i just need an example of where are they located on a traditional pandora instalation and i figure out where it is on my system. I installed pandora tru MO2 btw, sorry for the troubles.
