### ISSUE TITLE
[Bug]: Behavior Engine Refuses to Launch

### ISSUE THREAD

**Issue by ZenitharAmbi** [Monitor221hz/Pandora-Behaviour-Engine-Plus#275]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v.2.0.4.alpha

### Provide Instructions on Reproducing the Problem

I installed as a mod in MO2, added it to the dropdown menu. Hitting run only opened the menu the very first time and it hasn't opened since. Not even running the file directly or as Administrator gets it to launch. I've tried reinstalling several times with no luck.

### Provide Relevant Files

Unable to get an Engine.log file or produce an output.

### Provide Visual Proof (optional)

https://github.com/user-attachments/assets/fabac7ef-fa44-4273-b81d-03aa4b4d2d82

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Did you install .NET 8 runtime? Are there any mods in the overwrite folder?

**Comment by ZenitharAmbi** [comment]
Installed .Net 8 runtime manually, pandora didn't like that and made me install it from clicking the exe. it opened the window once and it hasn't since. the exe, the folder it's in, the folder the folder is in are all exceptions and even with WD off it still doesn't launch. tried with 2.0.4 (seen in video) and the last 1.6 version and both had the same result. Even a wabba list i downloaded that came with Pandora, it won't launch

**Comment by ZenitharAmbi** [comment]
Yeah, I'm think pandora just hates my computer. Even when i repaired Dotnet runtime 8.0.7 it still refuses to let pandora open.

**Comment by JamesATeasdale** [comment]
I'm having the same issue, I have even tried multiple dotnet8 versions.
I even deleted everything in the overwrite folder.
Dotnet8 seems to be a problem. Is there any way to run it headless yet?

**Comment by Monitor221hz** [comment]
This would be ridiculous if it were the solution, but has anyone tried having dotnet 7 installed as well 😅

**Comment by NefYmind** [comment]
having the same issue - Pandora force installed dotnet 8 for me

**Comment by JamesATeasdale** [comment]
> Right - I uninstalled .NET 5 and .NET 6, reinstalled, and it seems to be working fine.

This worked for me, I think. I installed and uninstalled so many different dotnets and one of the first dotnet8s I tried suddenly started working. I don't know why the most recent dotnets are so awful.



> this may be a dumb question but how do i go about finding & uninstalling dotnets

Open add or remove apps/programs on Windows and delete some dotnets. They're usually called Microsoft .NET or something like that. If you uninstall them then other games might not work, so make sure they're not dependencies for other games or apps.

**Comment by ZenitharAmbi** [comment]
> Open add or remove apps/programs on Windows and delete some dotnets. They're usually called Microsoft .NET or something like that. If you uninstall them then other games might not work, so make sure they're not dependencies for other games or apps.

welp... wish i could say this worked
still the same issue

**Comment by ZenitharAmbi** [comment]
.net runtime or desktop runtime btw?

**Comment by JamesATeasdale** [comment]
> .net runtime or desktop runtime btw?

Desktop runtime for guis/desktop applications like pandora

**Comment by ZenitharAmbi** [comment]
BIG PROGRESS
we're back at pandora getting me to install .net desktop runtime even though that's what i just reinstalled but it's progress
