### ISSUE TITLE
[Bug]: Engine crashes before parsing FNIS files

### ISSUE THREAD

**Issue by vitterra** [Monitor221hz/Pandora-Behaviour-Engine-Plus#276]
### Expected behavior

Automatic scanning FNIS files, as FNIS or Nemesis does.

### other

In the current implementation, Pandora does not see modifications that are already installed in the game.

**Comment by Monitor221hz** [comment]
> Automatic scanning FNIS files, as FNIS or Nemesis does.

What FNIS files? The animlists? The hkx files? You need to be more specific.

**Comment by vitterra** [comment]
Typically, animations were delivered as HKX files with their description for fnis in the form of a .txt file, for example: fnis_gs_slal_list.txt
Example: FNIS_AnimatedWeddingScene_List.txt:
Version V1.0

b -a,h WeddingRingA WeddingRingA.hkx
b -a,h WeddingRingB WeddingRingB.hkx

These files are copied directly in \DATA\Meshes\Actors\Character\Animations

**Comment by Monitor221hz** [comment]
> b -a,h WeddingRingA WeddingRingA.hkx

Yes, Pandora does see these animations and adds the animation paths to the character files, otherwise you would be seeing constant T-Pose. The majority of these animations are baked into an FNIS behavior file, which Pandora injects into the main graph. These are supported.

The ones that aren't baked into a standalone FNIS behavior need to be manually constructed into the behavior graph. For these, Pandora explicitly declares which types are unsupported (#76) and which ones have added support (#248).

I know how FNIS animlist files, Nemesis patches, and hkx files work, otherwise nobody would use this engine :P

**Comment by vitterra** [comment]
When the pandora is launched, are these animations considered?
I have more than 50 thousand animations in my system. And when the pandora launches are not visible in the log .. 0.
At the same time, Nemesis predicts and does not process some animations and Fnis does everything with a bang. But I want the advantages of Nemesis.
Without patches from Nemesis, Pandora does not see their animations - 0.

**Comment by Monitor221hz** [comment]
> When the pandora is launched, are these animations considered?

Yes. Are you running a prehistoric version of Pandora? Post the Engine.log and the output files

**Comment by vitterra** [comment]
Pandora:
[Engine.log.zip](https://github.com/user-attachments/files/16518321/Engine.log.zip)
Output files zero/none

Fnis on my system:
[fnis_output.txt.zip](https://github.com/user-attachments/files/16518322/fnis_output.txt.zip)
[fnis_temporary_logs.zip](https://github.com/user-attachments/files/16518323/fnis_temporary_logs.zip)
directory structure of skyrim se data folder:
[catalog.txt.zip](https://github.com/user-attachments/files/16518324/catalog.txt.zip)
nemesis on my system:
[Nemesis_Engine.zip](https://github.com/user-attachments/files/16518326/Nemesis_Engine.zip)

**Comment by Monitor221hz** [comment]
Did you disable FNIS and Nemesis outputs when you ran Pandora? The engine is crashing before it can produce an output.

**Comment by vitterra** [comment]
I did not see signs of falling, because if I turn on the Nenesis modules, he does something ..
But there are still no output files. OSTIM animations do not start, although they were connected and seemed to be picked up in Pandora.
I tried to turn off and leave the conclusion from Fnis. But the result is the same.

**Comment by Monitor221hz** [comment]
```
Содержимое папки G:\Games\TES V - Skyrim SE\Data\Pandora
05.08.2024  20:13    <DIR>          .
06.08.2024  18:52    <DIR>          ..
05.08.2024  20:13             3 719 Engine.log
02.08.2024  15:01            27 136 FastMember.Signed.dll
02.08.2024  15:01               131 FNIS.esp
02.08.2024  15:01           195 456 GongSolutions.WPF.DragDrop.dll
02.08.2024  15:01         1 390 592 HKX2E.dll
02.08.2024  15:01           497 136 HKX2E.pdb
05.08.2024  20:13    <DIR>          meshes
05.08.2024  19:26    <DIR>          Nemesis_Engine
02.08.2024  15:01             6 656 Nito.HashAlgorithms.Core.dll
02.08.2024  15:01            11 776 Nito.HashAlgorithms.CRC.dll
02.08.2024  15:01               463 NLog.config
02.08.2024  15:01           929 792 NLog.dll
05.08.2024  20:10             3 947 Pandora Behaviour Engine+.deps.json
02.08.2024  15:01         3 872 768 Pandora Behaviour Engine+.dll
02.08.2024  15:01           147 456 Pandora Behaviour Engine+.exe
02.08.2024  15:01           107 272 Pandora Behaviour Engine+.pdb
02.08.2024  15:01               458 Pandora Behaviour Engine+.runtimeconfig.json
05.08.2024  20:13    <DIR>          Pandora_Engine
05.08.2024  19:26    <DIR>          scripts
02.08.2024  15:01            34 816 XML Cake.dll
02.08.2024  15:01            27 620 XML Cake.pdb
```
here's your issue. you need to have Pandora exe in the data folder directly, not in its own folder.
