### ISSUE TITLE
[Bug]: user incompetence. Tried to follow the instructions and failed. Cant install in vortex.

### ISSUE THREAD

**Issue by mauricioGoes** [Monitor221hz/Pandora-Behaviour-Engine-Plus#281]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.0.4 - alpha

### Provide Instructions on Reproducing the Problem

Not sure if i should be posting this here, if not sorry. But all other places i searched people are running head first in the same issue and dont know how to fix. As in the disclaimer, i am probrably being dumb.

I donwloaded the zip. Extracted the zip. And tried to follow the instructions for vortex:

Install [.NET 8 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) if you do not have it installed. **->Done**
Add it to the tools dashboard.  **-> not sure how, there no exe**
2.a) It is highly recommended you set a custom output mod folder using -o:{path} in the 'Command Line' field. **-> I dont know what this mean. Tried anyway. I found an .snl file. Is that it to run the engine?**
![image](https://github.com/user-attachments/assets/4c0d97fc-dad5-49fa-81e9-fe6c6ae8a6de)

2.b) Ensure that the 'Start In' field is set to the Skyrim data directory. -> **ok i think**
Run the program either manually or after adding it to the tools dashboard. -> **How? there is no Exe.**

Am i downloading the wrong zip? i saw videos with the exe already in the zip file in them.

![image](https://github.com/user-attachments/assets/5e433273-016b-42ef-80b2-3e633651f9a3)

If anyone can instruct (step, by step for a first time modder) this dumb-dumb i would be thankfull.
Once again sorry if it is not the right place, but I dont know were else to ask.

### Provide Relevant Files

Failed to run tool

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
> Run the program either manually or after adding it to the tools dashboard. -> How? there is no Exe.

![image](https://github.com/user-attachments/assets/d859914c-c819-4db1-a524-73de20278f56)
