### ISSUE TITLE
[Bug]: Launch fails on first run but succeeds on second.

### ISSUE THREAD

**Issue by Kusoneko** [Monitor221hz/Pandora-Behaviour-Engine-Plus#285]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.1.4-alpha

### Provide Instructions on Reproducing the Problem

Updating from v1.6.3-alpha to v2.1.4-alpha:
- Remove Pandora_Output mod from MO2
- Remove Pandora v1.6.3 from MO2
- Add Pandora v2.1.4 to MO2 (including changing where the Pandora Executable is located and launched from in the MO2 Executables)
- Run Pandora v2.1.4 from MO2
- Select all (somehow some of the options are duplicated, no clue why, specifically: Precision Creatures, True Directional Movement - Procedural Leaning and XPMSE Patch For Pandora)
- Launch
- Receive CRITICAL FAILURE
(Optional)
- Launch again
- Works somehow?

Everything seemed to work fine on the first run using 1.6.3, however it was pretty outdated so as I was updating my setup I figured I'd take the opportunity to update Pandora as well.

I haven't tried yet if the output of the second launch works fine or not, I'll look into it when I have a minute, but I'm presuming it does.

### Provide Relevant Files

This is the first run:
[Pandora_Output.zip](https://github.com/user-attachments/files/16650490/Pandora_Output.zip)

This is when I rerun it immediately after and get a "normal" result:
[Pandora_Output.zip](https://github.com/user-attachments/files/16650508/Pandora_Output.zip)

Rerunning with the Output of the second one unticks one of each of the duplicates mentioned above (see screenshot below).

### Provide Visual Proof (optional)

![Screenshot 2024-08-18 132755](https://github.com/user-attachments/assets/e37d7d78-52ea-4397-9c1d-7fddcba999fc)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
` ---> System.IO.IOException: The process cannot access the file 'D:\SteamLibrary\steamapps\common\Skyrim Special Edition\data\Nemesis_Engine\mod\colisc\animationdatasinglefile\DraugrProject.txt' because it is being used by another process.`

On multiple runs of the engine (run being you closed and opened the engine exe through MO2), does it consistently fail on the first launch? Or was it just this one time when you updated from 1.6.3-alpha?

**Comment by Monitor221hz** [comment]
As for the duplicate patches, should be fixed in 2.1.5-alpha

**Comment by Kusoneko** [comment]
> ` ---> System.IO.IOException: The process cannot access the file 'D:\SteamLibrary\steamapps\common\Skyrim Special Edition\data\Nemesis_Engine\mod\colisc\animationdatasinglefile\DraugrProject.txt' because it is being used by another process.`
> 
> On multiple runs of the engine (run being you closed and opened the engine exe through MO2), does it consistently fail on the first launch? Or was it just this one time when you updated from 1.6.3-alpha?

It's every single time I remove the "Pandora Output" mod I create using whatever's in the Overwrite folder, then try to run the engine again, selecting all the mods in Pandora. Strangely, I can miss a mod inside Pandora's selection interface and it will run just fine somehow, then selecting the missing one and running it again so everything's there works just fine. I'm not quite sure why it says that file is being used by another process since there really shouldn't be anything using it when I run Pandora, besides Pandora.

I've played about 3 hours since and can confirm the animations work just fine, so it's purely an annoyance thing where I get to have to run it twice. Although, IOExceptions are usually Windows throwing that up, so I don't think there's much that can be done about it, besides an eventual reboot and hoping that fixes whatever broke. I will try rebooting later though, just in case. I also haven't met any draugr yet in the current playthrough, and considering the file at issue is a draugr file, if there's any issue it should be when meeting one or more of them.

Another side theory, but I can't really confirm it as I don't really know the code at all, could be that selecting duplicate patches means Pandora attempts to load the same files twice in a run, so the second time it's "in use"? Although, that doesn't explain why the second run it works fine... This is confusing.

**Comment by Monitor221hz** [comment]
> Another side theory, but I can't really confirm it as I don't really know the code at all, could be that selecting duplicate patches means Pandora attempts to load the same files twice in a run, so the second time it's "in use"? Although, that doesn't explain why the second run it works fine... This is confusing.

Can you confirm this problem exists in the latest version, where the duplicate patches issue should be fixed?

**Comment by Kusoneko** [comment]
> > Another side theory, but I can't really confirm it as I don't really know the code at all, could be that selecting duplicate patches means Pandora attempts to load the same files twice in a run, so the second time it's "in use"? Although, that doesn't explain why the second run it works fine... This is confusing.
> 
> Can you confirm this problem exists in the latest version, where the duplicate patches issue should be fixed?

Confirmed, both the duplicate patches and the first run error are fixed.

**Comment by Kusoneko** [comment]
Although, the log now starts with this, not quite sure what this all means:

```
ERROR : Nemesis Assembler > File D:\SteamLibrary\steamapps\common\Skyrim Special Edition\data\Nemesis_Engine\mod\colisc\draugrbehavior\#0115.txt > Load > FAILED > The 'hkobject' start tag on line 1 position 4 does not match the end tag of 'hkparam'. Line 11, position 5.
ERROR : Nemesis Assembler > File D:\SteamLibrary\steamapps\common\Skyrim Special Edition\data\Nemesis_Engine\mod\colisc\draugrbehavior\#0119.txt > Load > FAILED > The 'hkobject' start tag on line 1 position 4 does not match the end tag of 'hkparam'. Line 11, position 5.
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_netch_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_dragon_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_boarriekling_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_Babo Creature_dog_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_Babo Creature_dog_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_frostbitespider_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_spriggan_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.63 > File > FNIS_SexLabCreature_Bear_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_BaboMotionData_troll_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_sabrecat_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_chaurus_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_riekling_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_draugr_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_horse_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_Billyy_CreatureMisc_canine_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_canine_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_dog_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_wolf_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_Billyy_CreatureMisc_canine_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_skeever_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_canine_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_dog_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_wolf_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V5 > File > FNIS_Fillherup_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V4.1.0 > File > FNIS_DD3_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_FunnyBizCB_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > MD 0.0 0.0 0.0 0 > File > FNIS_BaboMotionData_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > MD 0.0 0.0 0.0 0 > File > FNIS_BaboMotionData_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > MD 0.0 0.0 0.0 0 > File > FNIS_BaboMotionData_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V5 > File > FNIS_Defeat_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V5.3 > File > FNIS_DDC_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.64 > File > FNIS_SexLabAP_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AnimVar SexLabAPAnimations INT32 16400 > File > FNIS_SexLabAP_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.64 > File > FNIS_SexLabCreature_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AnimVar SexLabCreature INT32 16400 > File > FNIS_SexLabCreature_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V7.2 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAprefix xpe > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _1hmeqp 5 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _2hmeqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _2hweqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _axeeqp 5 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _bowatk 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _boweqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _bowidle 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _maceqp 2 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _dageqp 6 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magatk 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magcastmt 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magcon 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magidle 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magmt 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _sprint 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _shout 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > T xpe3_Dag_Unequip.hkx Unequip_OutMoving -0.333 Unequip_Out -0.00 BeginWeaponSheathe 0.00 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > T xpe4_Dag_Unequip.hkx Unequip_OutMoving -0.333 Unequip_Out -0.00 BeginWeaponSheathe 0.00 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V4.0.0 > File > FNIS_DD2_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V5.3 > File > FNIS_DD_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.64 > File > FNIS_SexLab_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AnimVar SexLabFramework INT32 16400 > File > FNIS_SexLab_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AnimVar SexLabDefault INT32 16400 > File > FNIS_SexLab_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V1.0 > File > FNIS_SexLab_Aroused_Creatures_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V8.00 > File > FNIS_ZaZAnimationPack_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V8.00 > File > FNIS_ZaZAnimationPack+_List.txt
```

Everything seems to work fine aside from those warnings though.
