### ISSUE TITLE
[Bug]: Skeletons a-posing

### ISSUE THREAD

**Issue by Yrbaa** [Monitor221hz/Pandora-Behaviour-Engine-Plus#294]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.0 Alpha

### Provide Instructions on Reproducing the Problem

It's the same issue as was posted by me before. Even with the new version the skeletons in soul cairn are still a-posing. I have deleted the previous version completely (the output too)

### Provide Relevant Files

[Engine.zip](https://github.com/user-attachments/files/16752520/Engine.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
god dammit

**Comment by iwejfnd** [comment]
Just adding I'm also getting this issue with 2.3.0beta, all the non-human creatures in solstheim are a-posing. I don't have any creature animation packs.

**Comment by iwejfnd** [comment]
Still getting creatures a-posing, on v2.6.0-beta now

As a side note, a bunch of animation packs that previously caused CTD when loading a save no longer do so, so thanks for fixing that!
