### ISSUE TITLE
[Bug]: Game crash when use 2hand weapon killmove to a skeleton 

### ISSUE THREAD

**Issue by jacklittlecore** [Monitor221hz/Pandora-Behaviour-Engine-Plus#322]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.3.0

### Provide Instructions on Reproducing the Problem

1, use pandora,
2, find a skeleton
3, use two hand weapon，trigger killmove
4, game crash
5, change to fnis
6, not crash now

### Provide Relevant Files

[pandora output.zip](https://github.com/user-attachments/files/17455773/pandora.output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
Update to v2.3.5-alpha and see if the bug is fixed.
