### ISSUE TITLE
[Bug]: Started using Pandora, animation crashes

### ISSUE THREAD

**Issue by generaleagleyt** [Monitor221hz/Pandora-Behaviour-Engine-Plus#324]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

Pandora Behaviour Engine v2.3.0-beta 

### Provide Instructions on Reproducing the Problem

I use my own version of MGO VR modlist. Until today I was using a combination of Nemesis and FNIS. After I switched to Pandora, I started getting crashes as I travel around Skyrim. They weren't happening before. The one mentioned in 2 crashlogs happens everytime I walk from Standing stones to Riverwood. I'm looking for help to resolve this issue.

No fight was happening, at least not close to me where I would notice. 

### Provide Relevant Files

[PANDORA OUTPUT.zip](https://github.com/user-attachments/files/17481103/PANDORA.OUTPUT.zip)
These two crashlogs are from the same place.
[crash-2024-10-22-19-09-31.log](https://github.com/user-attachments/files/17481106/crash-2024-10-22-19-09-31.log)
[crash-2024-10-22-19-02-56.log](https://github.com/user-attachments/files/17481108/crash-2024-10-22-19-02-56.log)
This one is from a bit earlier in this save, didnt happen again yet.
[crash-2024-10-22-18-51-53.log](https://github.com/user-attachments/files/17481110/crash-2024-10-22-18-51-53.log)

None of these crashes happened before in my previous playthroughts.

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Kusoneko** [comment]
Not a dev, but the 2 former crashlogs seem to imply an issue with regards to the animation "Paired_VampFeedFront" in between the NPCs "Queen of Screams Sex Cultist" from "SeranaDeadSexyEXXXtendedCut.esp" and "Bandit" from "YurianaWench.esp", unless I'm misreading the logs?
The latter crash appears to be regarding the "Paired_1HMKillMoveDecapBleedOut" animation, and seems to mention the following NPCs: "Bandit Sickly" from "OBIS SE.esp" and "Cultist's Willing Sex Slave and Sacrifice" from "SeranaDeadSexyExpandedCults.esp".

BTW, I had a similar issue with the IdleCartDriverSway animation on my setup with 2.3.0-beta, although my crashlogs mentioned no specific NPCs, have you tested if it works fine using the generated output of 2.1.5-alpha? If it works fine when using the previous version it would lend credit to my issue ( #316 ) that there's seemingly a regression of some kind in between the output of pandora between 2.1.5-alpha and 2.3.0-beta.

**Comment by Monitor221hz** [comment]
Test the latest version (2.3.5-alpha as of the time of writing), and see if the issue is fixed.

**Comment by generaleagleyt** [comment]
> Test the latest version (2.3.5-alpha as of the time of writing), and see if the issue is fixed.

It happened again, using the version you mentioned. While using ASLAL, while waiting for mods to initialize, Ghost NPC added by 3DNPC mod was fighting with other enemy ghosts in Abandoned Prison. Again, that wasnt an issue before Pandora.

[crash-2024-10-27-17-25-14.log](https://github.com/user-attachments/files/17534816/crash-2024-10-27-17-25-14.log)
The animation mentioned is probably from Gunslicer OAR Animations Pack on Nexus

PANDORA OUTPUT link: https://ufile.io/icsps3x7 (30Mb, maximum upload here is 25Mb)

**Comment by generaleagleyt** [comment]
Also Pandora 2.4 built only 12k animations, while 2.3 built 65k (I have a lot I know)

**Comment by generaleagleyt** [comment]
> Test the latest version (2.3.5-alpha as of the time of writing), and see if the issue is fixed.

It looks like Pandora 2.4 is ignoring NSFW animations. Also regarding og issue, only that vampire feed animation and killmove animations are causing crashes, even after removing Gunslicer anim pack

**Comment by generaleagleyt** [comment]
Temporary fix: installed Violens mod from Nexus, in MCM disabled all killmoves for both PC and NPC.

**Comment by generaleagleyt** [comment]
Nevermind, still crashing on killmove animations

**Comment by generaleagleyt** [comment]
Please, I really need help. These killmove crashes keep happening. I disabled them with Violens, but scripted killmoves crash my game still (like the Markarth one)
[crash-2024-10-30-21-00-25.log](https://github.com/user-attachments/files/17579077/crash-2024-10-30-21-00-25.log)
[crash-2024-10-30-20-37-58.log](https://github.com/user-attachments/files/17579078/crash-2024-10-30-20-37-58.log)
[crash-2024-10-30-20-23-15.log](https://github.com/user-attachments/files/17579079/crash-2024-10-30-20-23-15.log)

**Comment by generaleagleyt** [comment]
SOLVED: the issue has to do with Open Animation Replacer and possibly Skyrim VR.
Found this comment on OAR Nexus page:

> awegaweg
> 
> It seems that
> 
> [Experimental]
> bIncreaseAnimationLimit = true
> 
> Causes my VR game to ctd everytime I feed as vampire. It also seems to happen when someone performs a killmove. A typical log is:
> https://pastebin.com/hGyZ47Nb
> 
> Changing it back to false fixes my crash. (on version 2.10)
> 
> Persumably this is related to paired animations. Whether this is VR specific, or whether this results from interaction of tons of mods, I do not know.

I had it set to true as well. I set it to false and no more crashing. But it started only after I switched to Pandora.
