### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by poperigby** [Monitor221hz/Pandora-Behaviour-Engine-Plus#327]
Do you think you could add an open source license to this project, so people are able to legally contribute to it? Thanks!

**Comment by Monitor221hz** [comment]
Hello, all versions prior to v2.3.0-beta are licensed under GNU GPL v3. 

I forgot to add a license in the latest tag because of the transition to Avalonia, but there's one now in the latest commit. Thanks for the reminder.

**Comment by poperigby** [comment]
Thanks!
