### ISSUE TITLE
[Bug]: Attack bugs and stucks animation while casting spell. 

### ISSUE THREAD

**Issue by Derackles** [Monitor221hz/Pandora-Behaviour-Engine-Plus#330]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.5

### Provide Instructions on Reproducing the Problem

When casting a spell on the left hand, attacking with the right hand one handed weapon stuck the character in position where you cant move or act. 

### Provide Relevant Files

[Engine.log](https://github.com/user-attachments/files/17505398/Engine.log)
[Pandora Output.zip](https://github.com/user-attachments/files/17505408/Pandora.Output.zip)

### Provide Visual Proof (optional)

[SkyrimSE_2024.10.24-12.08.webm](https://github.com/user-attachments/assets/3393fbf7-36ea-4c3f-8475-86866c6d4bdc)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by daisiesloves** [comment]
+1 I have the same problem.
