### ISSUE TITLE
[Bug]: PC and NPC plays wrong Animation

### ISSUE THREAD

**Issue by Derackles** [Monitor221hz/Pandora-Behaviour-Engine-Plus#331]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

2.3.5

### Provide Instructions on Reproducing the Problem

PC and NPC play irrelevant animation, such as staggers now some NSFW animation, other than that eating, sitting animations, etc all play different animations. The animation path is different from what i played according to OAR's animation log. For example, when i eat a food with eating animation mod, my character plays some attack animation from MCO moveset. Or when npc or PC staggered during combat, it plays random nsfw animation or attack animation. 

### Provide Relevant Files

[Engine.log](https://github.com/user-attachments/files/17505549/Engine.log)
[Pandora Output.zip](https://github.com/user-attachments/files/17505550/Pandora.Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor221hz** [comment]
v1.1+ of Precision Creatures is not compatible.

**Comment by WinterSouli** [comment]
Same issue but I don't have Precision Creatures. 
[Engine.log](https://github.com/user-attachments/files/17511117/Engine.log)
[Pandora Output.zip](https://github.com/user-attachments/files/17511146/Pandora.Output.zip)

**Comment by vexeixx** [comment]
> Same issue but I don't have Precision Creatures. [Engine.log](https://github.com/user-attachments/files/17511117/Engine.log) [Pandora Output.zip](https://github.com/user-attachments/files/17511146/Pandora.Output.zip)

sry for this info sending I am kinda new to all these stuff :)))

[Output.zip](https://github.com/user-attachments/files/17511186/Output.zip)

**Comment by Monitor221hz** [comment]
Check v2.4.0-beta, problem should be fixed.

**Comment by Monitor221hz** [comment]
confirmed to be fixed in v2.4.0-beta by original poster in discord
