### ISSUE TITLE
[Bug]: Doesn't see anim mods in MO2 SkyrimVR even with -tesv: set or registry changed (also have Skyrim SE installed)

### ISSUE THREAD

**Issue by barronj** [Monitor221hz/Pandora-Behaviour-Engine-Plus#346]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.4.0beta

### Provide Instructions on Reproducing the Problem

I installed Pandora v2.4.0beta from Nexus into MO2 for my Skyrim VR instance (Steam Version). I originally had Skyrim VR installed on C but switched to D a long time ago through the move install option in Steam rather than uninstall/reinstall. The OS is Windows 10.

I ran Pandora through MO2, but it saw none of my installed behavior mods (Flower girls and some DAR mods). I only see XPMSE Patch and Pandora Base. Note, this is a fairly clean install. I never had FNIS or NEMESIS in this installation.

I added the the following to the arguments section, -tesv:"D:\SteamLibrary\steamapps\common\SkyrimVR". Same behavior. I even went into the registry and changed the install location for Skyrim VR to this path, and I have the same issue. Note that I also have Skyrim SE installed on the computer.

When I do run it, I do see the following in the output area:

Engine launched with configuration: Skyrim SE/AE. Do not exit before the launch is finished.
Waiting for preload to finish.
Preload finished.

Pandora Mod 1 : XPMSE Patch For Pandora - v.1.0.0
Pandora Mod 2 : Pandora Base - v.1.0.0

FNIS Mod 1 : FNIS_XPMSE_List
FNIS Mod 2 : FNIS_FlowerGirlsSE_List

1379 animations added to defaultfemale.
1379 animations added to defaultmale.

2758 total animations added.

Launch finished in 4.36 seconds

[PandoraOutput.zip](https://github.com/user-attachments/files/17641257/PandoraOutput.zip)

### Provide Relevant Files

I attached the zip but will also copy the contents of engine.log to here:

WARN : Engine > Folder mod > Parse Info > xpmse Already Exists > SKIPPED
WARN : Engine > Folder mod > Parse Info > pandora Already Exists > SKIPPED
WARN : Engine > Folder mod > Parse Info > xpmse Already Exists > SKIPPED
WARN : Engine > Folder mod > Parse Info > pandora Already Exists > SKIPPED
INFO : Skyrim Patcher 2.4.0-beta
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/maxAnkleHeightMS > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/hipIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/kneeIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/ankleIndex > FAILED
WARN : Dispatcher > "Pandora Base" > dragonproject~dragonbehavior > Replace > Element > #0885/legs/Element0/isPlantedMS > FAILED
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V7.2 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAprefix xpe > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _1hmeqp 5 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _2hmeqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _2hweqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _axeeqp 5 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _bowatk 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _boweqp 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _bowidle 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _maceqp 2 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _dageqp 6 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magatk 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magcastmt 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magcon 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magidle 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _magmt 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _sprint 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > AAset _shout 1 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > T xpe3_Dag_Unequip.hkx Unequip_OutMoving -0.333 Unequip_Out -0.00 BeginWeaponSheathe 0.00 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > T xpe4_Dag_Unequip.hkx Unequip_OutMoving -0.333 Unequip_Out -0.00 BeginWeaponSheathe 0.00 > File > FNIS_XPMSE_List.txt
WARN : FNIS Animlist > New Animation > From Line > FAILED > Line > Version V3.0.2 > File > FNIS_FlowerGirlsSE_List.txt
INFO : Engine launched with configuration: Skyrim SE/AE. Do not exit before the launch is finished.
INFO : Pandora Mod 1 : XPMSE Patch For Pandora - v.1.0.0
INFO : Pandora Mod 2 : Pandora Base - v.1.0.0
INFO : FNIS Mod 1 : FNIS_XPMSE_List
INFO : FNIS Mod 2 : FNIS_FlowerGirlsSE_List
[PandoraOutput.zip](https://github.com/user-attachments/files/17641271/PandoraOutput.zip)

### Provide Visual Proof (optional)

![Screenshot 2024-11-05 202726](https://github.com/user-attachments/assets/f0506eb5-f00b-446a-b452-09c9108df928)
This is what I see when running the program

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by barronj** [comment]
Also note, when running the game, everyone is frozen in a t-pose as you would expect.

**Comment by Monitor221hz** [comment]
DAR mods are not supposed to be patched by the engine.
