### ISSUE TITLE
[Bug]: OAR Not Loading Animations

### ISSUE THREAD

**Issue by milk-withcookies** [Monitor221hz/Pandora-Behaviour-Engine-Plus#355]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v2.4.0-beta

### Provide Instructions on Reproducing the Problem

Enabling Pandora's Output in MO2 causes Open Animation Replacer to not load animations, causing every character to A-pose.

1. Run Pandora with the `-o` flag pointing to a MO2 mod
2. Make sure output mod is enabled
3. Make sure OAR is enabled
4. Launch Skyrim
5. Observe OAR greeting popup on main menu, but no animation loading bar
6. Start new game or load a save
7. Observe all characters A-posing

Disabling the output mod fixes the issue. The OAR animation loading bar shows up on the main menu and characters don't A-pose.

### Provide Relevant Files

[Pandora Output.zip](https://github.com/user-attachments/files/17690609/Pandora.Output.zip)
[Engine.log](https://github.com/user-attachments/files/17690611/Engine.log)
[modlist.txt](https://github.com/user-attachments/files/17690613/modlist.txt)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by milk-withcookies** [comment]
Turns out it was a random FNIS mod causing it. If anyone has this issue I would recommend the classic "disable all your mods then turn them back on one-by-one" gamer move.

**Comment by Lilac-Fear** [comment]
Do you remember which fnis mod was causing the issue?
